# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.4.0
_src_path: https://github.com/jupyterlab/extension-template
author_email: leductrungxf@gmail.com
author_name: Trung Le
has_binder: false
has_settings: false
kind: frontend
labextension_name: jupyter-monstra
project_short_description: A JupyterLab extension.
python_name: monstra
repository: https://github.com/trungleduc/monstra
test: false

